[package]
name = "psx_vislist_generator"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
byteorder = "1.4.3"
gl = "0.14.0"
glam = "0.24.1"
glfw = "0.52.0"
image = "0.24.7"
memoffset = "0.9.0"
